config/routes.rb
AlwaysNote::Application.routes.draw do
  get 'users/authenticate', to: 'users#authenticate'
  get 'users/forgot_password', to: 'users#forgot_password'
  get 'users/send_password', to: 'users#send_password'
  resources :users, :only => [:create, :new, :show, :update, :edit]
  resource :session, :only => [:create, :new]
  get 'session/logout', to: 'sessions#destroy'
  root to: 'root#root'
  resources :notebooks, :only => [:create, :destroy, :show, :index, :update]
  resources :notes, :only => [:create, :destroy, :show, :index, :update]
  resources :tags, :only => [:create, :destroy, :index]
  resources :contributions, :only => [:create, :destroy]
end

app/models/user.rb
class User < ActiveRecord::Base
  
  require 'bcrypt'
  
  attr_accessible :username, :password, :email
  attr_reader :password
  
  validates :username, :password_digest, :email, :presence => true
  validates :password, :length => { :minimum => 6 }
  validates_format_of :username, :with => /\A[-a-zA-Z0-9]+\Z/
  validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
  validates_uniqueness_of :username, :base_email, :case_sensitive => false
  
  has_many :owned_notebooks, :class_name => "Notebook", :foreign_key => :owner_id
  has_many :contributions, :dependent => :destroy
  has_many :notebooks, :through => :contributions, :source => :notebook
  has_many :notes, :class_name => "Note", :foreign_key => :owner_id
  
  
  def set_auth_token!
    self.auth_token = SecureRandom.urlsafe_base64(16)
  end
  
  def password
    @password || self.password_digest
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def verify_password(password)
    BCrypt::Password.new(self.password_digest) == password
  end
  
  def set_base_email!
    if self.email.include?("+")
      new_email = self.email.split("+")
      base_email = "" + new_email.first + "@"
      new_email.each do |section|
        if section.include?("@")
          base_email += section.split("@").last
        end
      end
      self.base_email = base_email
    else
      self.base_email = self.email
    end
  end
  
  def to_json
    super(:only => [:username, :id])
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def create
    @user = User.new(params[:user])
    @user.set_auth_token!
    @user.set_base_email!
    if @user.save
      login_user!(@user)
      Notifier.signup_email(@user).deliver
      redirect_to root_url
    else
      render :new
    end
  end
  
  def new
    @user = User.new
    render :new
  end
  
  def authenticate
    @user = User.find_by_auth_token(params[:auth_token])
    if @user
      @user.set_auth_token!
      @user.authenticated = true
      @user.save
      login_user!(@user)
      redirect_to root_url
    else
      redirect_to new_user_url
      #change this to something else later?
    end
  end
  
  def edit
    @user = User.find_by_id(params[:id])
    render :new_password
  end
  
  def update
    @user = User.find_by_id(params[:id])
    if @user && @user.verify_password(params[:user][:old_password])
      @user.password = params[:user][:new_password]
      @user.save
      redirect_to root_url
    else
      redirect_to new_session_url
    end
  end
  
  def forgot_password
    render :forgot_password
  end
  
  def send_password
    @user = User.find_by_username(params[:user][:username])
    if @user
      Notifier.forgot_password_email(@user).deliver
    end
    redirect_to root_url
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/forgot_password.html.erb
<h1>Reset Password</h1>
An email will be sent to you containing a temporary password.
<br>
<form action="<%= users_send_password_url %>" method="get">
	<label for="user_username">Username</label>
	<input type="text" name="user[username]" id="user_username">
	<br>
	<input type="submit" value="Reset Password">
</form>

app/views/users/new.html.erb
<div class="static_page">
	<div class="static_page_logo">
		AlwaysNote
	</div>
	
	<div class="sign_up">
		<h1>Sign Up!</h1>

		<form class="login" action="<%= users_url %>" method="POST">
			<label for="user_email">Email</label>
			<input type="text" name="user[email]"
				id="user_email" value="<%= @user.email %>">
			<br>
			<label for="user_username">Username</label>
			<input type="text" name="user[username]" 
				id="user_username" value="<%= @user.username %>">
			<br>
			<label for="user_password">Password</label>
			<input type="password" name="user[password]" id="user_password">
			<input type="hidden" name="authenticity_token" 
				value="<%= form_authenticity_token %>">
			<br>
			<input type="submit" id="submit" value="Sign Up">
		</form>
		
		<div class="signed_up">
			Already have an account? <a href="/session/new">Sign in!</a>
		</div>
	</div>
</div>

app/views/users/new_password.html.erb
<h1>Reset Your Password</h1>

<form action="<%= user_url %>" method="POST">
	<label for="user_old_password">Old Password</label>
	<input type="password" id="user_old_password" name="user[old_password]">
	<br>
	<label for="user_new_password">New Password</label>
	<input type="password" id="user_new_password" name="user[new_password]">
	<br>
	<input type="hidden" name="authenticity_token"
		value="<%= form_authenticity_token %>">
	<input type="hidden" name="_method" value="put">
	<input type="submit" value="Change Password">
</form>

app/views/users/show.html.erb
<h1>Thanks for signing up!</h1>
<p>A link to verify your account will be emailed to you shortly.</p>